name: continuous-deployment

on:
  push:
    branches:
      - main

env:
  TFM_DIR: "terraform"
  CFG_DIR: "configuration"

jobs:
  # CALL WORKFLOW tag-release
  tag-release:
    uses: indigo-tangerine/shared-workflows/.github/workflows/tag-release.yml@main

  # CALL WORKFLOW changelog
  update-changelog:
    needs: [tfm-plan-apply]
    uses: indigo-tangerine/shared-workflows/.github/workflows/update-changelog.yml@main
    secrets:
      access_token: ${{ secrets.CICD_AUTOMATION_PAT }}

  # CALL WORKFLOW tfm-plan-apply
  tfm-plan-apply:
    needs: [tag-release]
    uses: indigo-tangerine/shared-workflows/.github/workflows/tfm-plan-apply.yml@main
    with:
      configuration-dir: configuration
      terraform-dir: terraform
      aws-region: "eu-west-1"
    secrets:
      aws-access-key-id: ${{ secrets.CICD_AUTOMATION_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.CICD_AUTOMATION_AWS_SECRET_ACCESS_KEY }}
      aws-cicd-automation-role-external-id: ${{ secrets.ITC_AWS_IAM_EXTERNAL_ID }}
      aws-cicd-automation-github-role: ${{ secrets.CICD_AUTOMATION_GITHUB_ACTIONS_ROLE }}
