name: continuous-integration-fb

on:
  push:
    paths:
      - "configuration/**"
      - "terraform/**"
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      auto-apply:
        description: "Run workflow manually"
        required: false
        default: false
        type: boolean

env:
  TFM_DIR: "terraform"
  CFG_DIR: "configuration"

jobs:
  # CALL WORKFLOW tfm-validate-plan code validation and lint
  validate-iac:
    uses: indigo-tangerine/shared-workflows/.github/workflows/tfm-validate.yml@main
    with:
      terraform-dir: terraform

  # CALL WORKFLOW tfm-security tfsec scan
  security-scan:
    uses: indigo-tangerine/shared-workflows/.github/workflows/tfm-security.yml@main
    with:
      terraform-dir: terraform

  # CALL WORKFLOW tfm-plan
  tfm-plan:
    uses: indigo-tangerine/shared-workflows/.github/workflows/tfm-plan.yml@main
    needs: [validate-iac, security-scan]
    with:
      configuration-dir: configuration
      terraform-dir: terraform
      aws-region: "eu-west-1"
    secrets:
      aws-access-key-id: ${{ secrets.CICD_AUTOMATION_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.CICD_AUTOMATION_AWS_SECRET_ACCESS_KEY }}
      aws-cicd-automation-role-external-id: ${{ secrets.ITC_AWS_IAM_EXTERNAL_ID }}
      aws-cicd-automation-github-role: ${{ secrets.CICD_AUTOMATION_GITHUB_ACTIONS_ROLE }}
      snyk-token: ${{ secrets.SNYK_TOKEN }}
